#include "extension.glsl"

#define STAGE_VERTEX   0
#define STAGE_FRAGMENT 1

#define PROGRAM_BASIC               1
#define PROGRAM_TEXTURED            2
#define PROGRAM_TEXTURED_LIT        3
#define PROGRAM_SKYBASIC            4
#define PROGRAM_SKYTEXTURED         5
#define PROGRAM_CLOUDS              6
#define PROGRAM_TERRAIN             7
#define PROGRAM_TERRAIN_SOLID       8
#define PROGRAM_TERRAIN_CUTOUT_MIP  9
#define PROGRAM_TERRAIN_CUTOUT     10
#define PROGRAM_DAMAGEDBLOCK       11
#define PROGRAM_WATER              12
#define PROGRAM_BLOCK              13
#define PROGRAM_BEACONBEAM         14
#define PROGRAM_ITEM               15
#define PROGRAM_ENTITIES           16
#define PROGRAM_ARMOR_GLINT        17
#define PROGRAM_SPIDEREYES         18
#define PROGRAM_HAND               19
#define PROGRAM_WEATHER            20
#define PROGRAM_COMPOSITE          21
#define PROGRAM_COMPOSITE1         22
#define PROGRAM_COMPOSITE2         23
#define PROGRAM_COMPOSITE3         24
#define PROGRAM_COMPOSITE4         25
#define PROGRAM_COMPOSITE5         26
#define PROGRAM_COMPOSITE6         27
#define PROGRAM_COMPOSITE7         28
#define PROGRAM_FINAL              29
#define PROGRAM_SHADOW             30
#define PROGRAM_SHADOW_SOLID       31
#define PROGRAM_SHADOW_CUTOUT      32
#define PROGRAM_DEFERRED           33
#define PROGRAM_DEFERRED1          34
#define PROGRAM_DEFERRED2          35
#define PROGRAM_DEFERRED3          36
#define PROGRAM_DEFERRED4          37
#define PROGRAM_DEFERRED5          38
#define PROGRAM_DEFERRED6          39
#define PROGRAM_DEFERRED7          40

#define WORLD_NETHER    -1
#define WORLD_OVERWORLD  0
#define WORLD_END        1
