#define STAGE_ISVERTEX   (STAGE == STAGE_VERTEX)
#define STAGE_ISFRAGMENT (STAGE == STAGE_FRAGMENT)

#define WORLD_ISNETHER    (defined WORLD && WORLD == WORLD_NETHER)
#define WORLD_ISOVERWORLD (defined WORLD && WORLD == WORLD_OVERWORLD)
#define WORLD_ISEND       (defined WORLD && WORLD == WORLD_END)

#include "syntax.glsl"
